package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3 2011-03-11T14:28:00.250+08:00
 * Generated source version: 2.3.3
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ISoamSvc")
@XmlSeeAlso({ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.echosvclib.ObjectFactory.class})
public interface ISoamSvc {

    @WebResult(name = "EchoDataResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISoamSvc/EchoData", output = "http://tempuri.org/ISoamSvc/EchoDataResponse")
    @RequestWrapper(localName = "EchoData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EchoData")
    @WebMethod(operationName = "EchoData", action = "http://tempuri.org/ISoamSvc/EchoData")
    @ResponseWrapper(localName = "EchoDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EchoDataResponse")
    public java.lang.Integer echoData(
            @WebParam(name = "dataClientId", targetNamespace = "http://tempuri.org/") java.lang.String dataClientId
    );

    @WebResult(name = "GenerateLoadResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISoamSvc/GenerateLoad", output = "http://tempuri.org/ISoamSvc/GenerateLoadResponse")
    @RequestWrapper(localName = "GenerateLoad", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateLoad")
    @WebMethod(operationName = "GenerateLoad", action = "http://tempuri.org/ISoamSvc/GenerateLoad")
    @ResponseWrapper(localName = "GenerateLoadResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateLoadResponse")
    public org.datacontract.schemas._2004._07.echosvclib.StatisticInfo generateLoad(
            @WebParam(name = "runMilliSeconds", targetNamespace = "http://tempuri.org/") java.lang.Double runMilliSeconds,
            @WebParam(name = "dummyData", targetNamespace = "http://tempuri.org/") byte[] dummyData,
            @WebParam(name = "fileData", targetNamespace = "http://tempuri.org/") java.lang.String fileData
    );

    @WebResult(name = "EchoResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISoamSvc/Echo", output = "http://tempuri.org/ISoamSvc/EchoResponse")
    @RequestWrapper(localName = "Echo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Echo")
    @WebMethod(operationName = "Echo", action = "http://tempuri.org/ISoamSvc/Echo")
    @ResponseWrapper(localName = "EchoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EchoResponse")
    public java.lang.String echo(
            @WebParam(name = "input", targetNamespace = "http://tempuri.org/") java.lang.String input
    );

    @WebResult(name = "SoamInvokeResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/ISoamSvc/SoamInvoke", output = "http://tempuri.org/ISoamSvc/SoamInvokeResponse")
    @RequestWrapper(localName = "SoamInvoke", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SoamInvoke")
    @WebMethod(operationName = "SoamInvoke", action = "http://tempuri.org/ISoamSvc/SoamInvoke")
    @ResponseWrapper(localName = "SoamInvokeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SoamInvokeResponse")
    public byte[] soamInvoke(
            @WebParam(name = "SoamInput", targetNamespace = "http://tempuri.org/") byte[] soamInput
    );

}
